site_name: {{ cookiecutter.project_name }} Documentation
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}/
copyright: 2020 - Jakub Wlodek
nav:
  - Home: index.md
  - Installation: install.md
  - Basic Usage: usage.md
  - About: about.md
theme: readthedocs